master:
    extends:
        file: db-node.yml
        service: db-node
    environment:
        DB_PORT: 5999
        NODE_NAME: node1
    net: container:etcd
    volumes:
        - /tmp/node1:/pg.data

slave:
    image: governor_master
    extends:
        file: db-node.yml
        service: db-node
    environment:
        DB_PORT: 5998
        NODE_NAME: node2
    net: container:etcd
    volumes:
        - /tmp/node2:/pg.data

etcd:
    image: quay.io/coreos/etcd:v2.0.13
    volumes:
        - '/tmp/etcd:/data'
    expose:
        - 4001
    command: --data-dir /data --name etcd --advertise-client-urls http://127.0.0.1:4001 --listen-client-urls http://0.0.0.0:4001
