master:
    build: .
    volumes:
        - '/tmp/master:/pg.data'
        - './example.initdb.d:/docker-entrypoint-initdb.d'
    expose:
        - 5999
    net: container:etcd
    command: >
        python3 governor.py
        --dbname postgres
        --data-dir /pg.data
        --listen-address 0.0.0.0:5999
        --advertise-url=127.0.0.1:5999
        --etcd-url=http://127.0.0.1:4001
        -c wal_level=hot_standby
        -c max_wal_senders=5
        -c wal_keep_segments=8
        -c archive_timeout=1800s
        -c max_replication_slots=5
        -c hot_standby=on
    #-c archive_mode=on
    #-c logging_collector=on
    #-c archive_command='mkdir -p /wal_archive && cp %p /wal_archive/%f'

slave:
    image: governor_master
    volumes:
        - '/tmp/slave:/pg.data'
        - './example.initdb.d:/docker-entrypoint-initdb.d'
    expose:
        - 5998
    net: container:etcd
    command: >
        python3 governor.py
        --dbname postgres
        --data-dir /pg.data
        --listen-address 0.0.0.0:5998
        --advertise-url=127.0.0.1:5999
        --etcd-url=http://127.0.0.1:4001
        -c wal_level=hot_standby
        -c max_wal_senders=5
        -c wal_keep_segments=8
        -c archive_timeout=1800s
        -c max_replication_slots=5
        -c hot_standby=on
    #-c archive_mode=on
    #-c logging_collector=on
    #-c archive_command='mkdir -p /wal_archive && cp %p /wal_archive/%f'

etcd:
    image: quay.io/coreos/etcd:v2.0.13
    volumes:
        - '/tmp/etcd:/data'
    expose:
        - 4001
    command: --data-dir /data --name etcd --advertise-client-urls http://127.0.0.1:4001 --listen-client-urls http://0.0.0.0:4001
