master:
    build: .
    volumes:
        - '/tmp/master:/pg.data'
    ports:
        - '5999:5999'
    links:
        - etcd
    command: python3 governor.py --data-dir "$PGDATA" --listen-address 0.0.0.0:5999 --advertise-url=10.176.160.104:5999 --etcd-url=http://etcd:4001 --allow-address=10.176.160.104/16

#slave:
    #build: .
    #volumes:
        #- /tmp/slave:/pg.data
    #expose:
        #- 5432
    #command: postgres -i

etcd:
    image: quay.io/coreos/etcd:v2.0.13
    volumes:
        - '/tmp/etcd:/data'
    expose:
        - 4001
    command: --data-dir /data --name etcd --advertise-client-urls http://127.0.0.1:4001 --listen-client-urls http://0.0.0.0:4001
